### PR TITLE
pkg/importer: allow to skip paid API calls

### LINKED ISSUE #1731: Swarm API serves 402 for downloading images
Swarm importer is spitting out errors like

```
2025/10/24 03:11:29 Foursquare importer: error importing photos for checkin XXX: Get request on https://api.foursquare.com/v2/<reducted> failed with: 402 Payment Required
```

-- we need to back off -- or don't even try after having a first such error.

### PR DESCRIPTION
**Pull request by radkat**
Fixes #1731

### CODE REVIEW

File: pkg/importer/importer.go [hunk 1]
```diff
@@ -342,6 +342,10 @@ type RunContext struct {
 	lastProgress *ProgressMessage
 }
 
+func (rc *RunContext) UsePaidAPI() bool {
```
Comment (bradfitz) [inline pkg/importer/importer.go:353]: document this

File: pkg/importer/importer.go [hunk 2]
```diff
@@ -1132,6 +1136,7 @@ type importerAcct struct {
 	lastRunErr   error
 	lastRunStart time.Time
 	lastRunDone  time.Time
+	usePaidAPI   bool // whether to use the paid API(s) when retrieving data
```
Comment (bradfitz) [inline pkg/importer/importer.go:1147]: whether to use API endpoints (if any) that may require paying/credits

File: pkg/importer/swarm/swarm.go [hunk 3]
```diff
@@ -282,10 +289,21 @@ func (r *run) importCheckins() error {
...
 			}
 
-			err = r.importPhotos(placeNode, dup)
-			if err != nil {
-				r.errorf("Foursquare importer: error importing photos for checkin %s: %v", checkin.Id, err)
-				continue
+			if r.RunContext.UsePaidAPI() {
+				err = r.importPhotos(placeNode, dup)
+				if err != nil {
+					isPaidErr := strings.Contains(err.Error(), "402 Payment Required")
```
Comment (bradfitz) [inline pkg/importer/swarm/swarm.go]: should only check the status code here, not the undefined english

Comment (bradfitz) [reply pkg/importer/swarm/swarm.go]: See https://go.dev/blog/go1.13-errors for %w etc

File: pkg/importer/importer.go (hunk 2 above)
Comment (radkat) [reply pkg/importer/importer.go:1147]: Now there's a separate bool (on the higher level, of the importer) that specifies whether or not there are paid APIs. This boolean now controls whether or not to use them.

File: pkg/importer/importer.go [hunk 4]
```diff
@@ -124,6 +124,12 @@ type Properties struct {
 	// For example, this is "foursquare" for "swarm", so "swarm" shows
 	// in the UI and URLs, but it's "foursquare" in permanodes.
 	PermanodeImporterType string
+
+	// SupportsPaidAPI specifies whether this service has paid API(s)
+	// that we might need to use to extract data.
+	// Whether or not to use such paid API(s) is determined for each
+	// run of each importer's account by the user.
+	SupportsPaidAPI bool
```
Comment (bradfitz) [inline pkg/importer/importer.go]: how about "HasPaidAPI" 

Or really, this is about APIs that are mixed paid and non-paid, right? If it were just all paid, you wouldn't add it at all as an importer if you hadn't paid to get an API key.

So is this "HasSomePaidAPI" ?

File: pkg/importer/importer.go [hunk 5]
```diff
@@ -342,6 +348,12 @@ type RunContext struct {
 	lastProgress *ProgressMessage
 }
 
+// UsePaidAPI returns `true` if the run is going to use the paid API(s) when retrieving data.
```
Comment (bradfitz) [inline pkg/importer/importer.go]: The typical Go way to document boolean functions is "reports whether" instead of "returns true if"

Comment (bradfitz) [inline pkg/importer/importer.go]: and instead of "use the paid API(s)" let's say "use any optional paid APIs when"

File: pkg/importer/importer.go [hunk 6]
```diff
@@ -1188,6 +1201,12 @@ func (ia *importerAcct) RefreshInterval() time.Duration {
 	return d
 }
 
+// UsePaidAPI returns `true` if the importer is going to use the paid API(s) when retrieving data.
```
Comment (bradfitz) [inline pkg/importer/importer.go]: reports whether

File: pkg/importer/importer.go [hunk 7]
```diff
@@ -1188,6 +1201,12 @@ func (ia *importerAcct) RefreshInterval() time.Duration {
...
+// Returns `false` otherwise.
```
Comment (bradfitz) [inline pkg/importer/importer.go]: can remove this line. But in general Go uses complete sentences ("It returns false otherwise.")

File: pkg/importer/swarm/swarm.go [hunk 8]
```diff
@@ -282,10 +293,20 @@ func (r *run) importCheckins() error {
...
-			err = r.importPhotos(placeNode, dup)
-			if err != nil {
-				r.errorf("Foursquare importer: error importing photos for checkin %s: %v", checkin.Id, err)
-				continue
+			if r.RunContext.UsePaidAPI() {
+				err = r.importPhotos(placeNode, dup)
+				if err != nil {
+					isPaidErr := errors.Is(err, ErrPaymentRequired)
+					if isPaidErr {
+						if !showedPaidErrOnce {
```
Comment (bradfitz) [inline pkg/importer/swarm/swarm.go]: In the case where we did already warn and it's a paid error, shouldn't we stop importing photos on future runs? That is, line 296 should be:

if r.RunContext.UsePaidAPI() && !showedPaidErrOnce {

?

Comment (radkat) [reply pkg/importer/swarm/swarm.go]: Yeah, that's a good point. Prevent unnecessary calls.

File: pkg/importer/importer.go [hunk 9]
```diff
@@ -124,6 +124,12 @@ type Properties struct {
 	// For example, this is "foursquare" for "swarm", so "swarm" shows
 	// in the UI and URLs, but it's "foursquare" in permanodes.
 	PermanodeImporterType string
+
+	// HasSomePaidAPI specifies whether this service has paid API(s)
+	// that we might need to use to extract data.
```
Comment (bradfitz) [inline pkg/importer/importer.go]: has part of its API requiring payment or quota for optional bits of data (such as Swarm venue photos).

**Review by bradfitz — APPROVED** [review]
